apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: exchange-kafka
  namespace: telemetry
spec:
  kafka:
    version: 4.1.0
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "4.1"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: exchange-simulator-user
  namespace: telemetry
  labels:
    strimzi.io/cluster: exchange-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: market-events
          patternType: literal
        operations:
          - Write
          - Describe
      - resource:
          type: topic
          name: simulator-audit
          patternType: literal
        operations:
          - Write
          - Describe
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: eve-forwarder-user
  namespace: telemetry
  labels:
    strimzi.io/cluster: exchange-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: suricata-eve
          patternType: literal
        operations:
          - Write
          - Describe
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: indexer-worker-user
  namespace: telemetry
  labels:
    strimzi.io/cluster: exchange-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: market-events
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: topic
          name: simulator-audit
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: topic
          name: suricata-eve
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: indexer-worker
          patternType: literal
        operations:
          - Read
          - Describe
