apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      tenant: tenant-template
    includeSelectors: true

patches:
  - target:
      kind: Namespace
      name: telemetry
    patch: |-
      - op: add
        path: /metadata/labels/tenant
        value: tenant-template
  - target:
      kind: Namespace
      name: security
    patch: |-
      - op: add
        path: /metadata/labels/tenant
        value: tenant-template
