apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/example/exchange-simulator
    newName: ghcr.io/example/exchange-simulator
    newTag: dev
  - name: ghcr.io/example/eve-forwarder
    newName: ghcr.io/example/eve-forwarder
    newTag: dev
  - name: ghcr.io/example/indexer-worker
    newName: ghcr.io/example/indexer-worker
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: exchange-simulator
      namespace: telemetry
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: indexer-worker
      namespace: telemetry
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
